[package]
name = "convert-spatialmos-data-archive"
version = "0.1.0"
authors = ["Daniel Naschberger <daniel@naschi.at>"]
edition = "2018"

[dependencies]
chrono = "0.4.10"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
